spring:
  application:
    name: task-management-cli
  main:
    web-application-type: none

cli:
  api:
    base-url: ${API_BASE_URL:http://localhost:8080/api}
  auth:
    google:
      client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
